### ISSUE TITLE
Uncaught TypeError: t is not a constructor

### ISSUE THREAD

**Issue by cloydlau** [privatenumber/vue-2-3#3]
Hello, I did what the doc said but error occured. (Using in Vue-Cli)

```
Uncaught TypeError: t is not a constructor
    at Proxy.mounted (to-vue-3.js)
```

Here is the minimal reproducible demo:
https://codesandbox.io/s/vigilant-leakey-u00rf?file=/src/App.vue

In Vite either:
```
Uncaught Error: Vue 2 & 3 were not resolved with bare specifiers "vue" & "vue3". Register them with toVue3.register(Vue2, Vue3)
    at d (to-vue-3.js:1)
```

**Comment by privatenumber** [comment]
Thanks for the reproduction link.

The problem is with your project setup rather than with vue-2-3. `vue2` is pointing to [this package](https://www.npmjs.com/package/vue2) which isn't actually Vue. CodeSandbox doesn't seem to support package aliasing right now so I opened a feature request [here](https://github.com/codesandbox/codesandbox-client/issues/5324).

If your project is local, alias vue2 to the actual Vue by doing: `npm install vue2@npm:vue@^2.6.12`

You can see JsonEditorVue successfully run in a Vue3 app [here](https://codepen.io/privatenumber/pen/vYXpRyN?editors=0010).
